version: "3.9"

services:
  golang:
    build: .
    image: golang
    user: root
    working_dir: /app
    volumes:
      - ./:/app
    container_name: rh_api_test
    tty: true
    stdin_open: true
    command: bash
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - test
  redis:
    container_name: redis
    image: redis:7.0.2-alpine
    restart: always
    networks:
      - test
  db:
    container_name: rh_db_test
    image: postgres
    platform: linux/x86_64
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ./db/migrations/000001_funcionarios.up.sql:/docker-entrypoint-initdb.d/000001_funcionarios.up.sql
    networks:
      - test
networks:
  test:
    driver: bridge