// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocksusecase

import (
	context "context"

	customerror "github.com/beto-ouverney/rh-api/customerror"
	entity "github.com/beto-ouverney/rh-api/entity"

	mock "github.com/stretchr/testify/mock"
)

// IFuncionariosUseCase is an autogenerated mock type for the IFuncionariosUseCase type
type IFuncionariosUseCase struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *IFuncionariosUseCase) GetAll(ctx context.Context) (*[]entity.Funcionario, *customerror.CustomError) {
	ret := _m.Called(ctx)

	var r0 *[]entity.Funcionario
	if rf, ok := ret.Get(0).(func(context.Context) *[]entity.Funcionario); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.Funcionario)
		}
	}

	var r1 *customerror.CustomError
	if rf, ok := ret.Get(1).(func(context.Context) *customerror.CustomError); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*customerror.CustomError)
		}
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *IFuncionariosUseCase) GetByID(ctx context.Context, id string) (*entity.Funcionario, *customerror.CustomError) {
	ret := _m.Called(ctx, id)

	var r0 *entity.Funcionario
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Funcionario); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Funcionario)
		}
	}

	var r1 *customerror.CustomError
	if rf, ok := ret.Get(1).(func(context.Context, string) *customerror.CustomError); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*customerror.CustomError)
		}
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, funcionario
func (_m *IFuncionariosUseCase) Register(ctx context.Context, funcionario entity.Funcionario) (*int64, *customerror.CustomError) {
	ret := _m.Called(ctx, funcionario)

	var r0 *int64
	if rf, ok := ret.Get(0).(func(context.Context, entity.Funcionario) *int64); ok {
		r0 = rf(ctx, funcionario)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}

	var r1 *customerror.CustomError
	if rf, ok := ret.Get(1).(func(context.Context, entity.Funcionario) *customerror.CustomError); ok {
		r1 = rf(ctx, funcionario)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*customerror.CustomError)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewIFuncionariosUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewIFuncionariosUseCase creates a new instance of IFuncionariosUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIFuncionariosUseCase(t mockConstructorTestingTNewIFuncionariosUseCase) *IFuncionariosUseCase {
	mock := &IFuncionariosUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
