// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	customerror "github.com/beto-ouverney/rh-api/customerror"
	mock "github.com/stretchr/testify/mock"
)

// IContrachequeController is an autogenerated mock type for the IContrachequeController type
type IContrachequeController struct {
	mock.Mock
}

// GetByFuncionarioID provides a mock function with given fields: ctx, funcionaarioID
func (_m *IContrachequeController) GetByFuncionarioID(ctx string, funcionaarioID string) ([]byte, *customerror.CustomError) {
	ret := _m.Called(ctx, funcionaarioID)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = rf(ctx, funcionaarioID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 *customerror.CustomError
	if rf, ok := ret.Get(1).(func(string, string) *customerror.CustomError); ok {
		r1 = rf(ctx, funcionaarioID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*customerror.CustomError)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewIContrachequeController interface {
	mock.TestingT
	Cleanup(func())
}

// NewIContrachequeController creates a new instance of IContrachequeController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIContrachequeController(t mockConstructorTestingTNewIContrachequeController) *IContrachequeController {
	mock := &IContrachequeController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
